version: '3.8'

services:
  core:
    container_name: php-symfony
    build:
      context: ./docker
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: bash -c "composer install && symfony serve"
    ports:
      - "8000:8000"
